name: Publish to PyPI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry


      - name: Get version from pyproject.toml
        id: get_version
        run: |
            VERSION=$(poetry version -s)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install dependencies
        run: poetry install --no-root --no-dev

      # - name: Build and publish
      #   if: github.event_name == 'push'
      #   run: |
      #     poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      #     poetry publish --build
      
      - name: Create Release with generate note
        if: github.event_name == 'push'
        run: gh release create v${{ env.VERSION }} --generate-notes
